# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


data_config:
  random_rotation: 5
  crop: True
  horizontal_flip: True
  affine: True
  color_jitter: True
  validation_split: 0.9
  batch_size: 256
  num_workers: 0
  resnet_blocks: [1, 1, 1, 1]
  block_channel:  [64, 128, 256, 512]
  input_channel: 64
  data_path: /Users/vaibhavsingh/Desktop/NYU/DL project/Mini_Project_2022/saved_models # Change this according to your root.
  saved_model: /Users/vaibhavsingh/Desktop/NYU/DL project/Mini_Project_2022/saved_models/model_512_SGD_ROP_256.pt

train_config:
  optimiser: SGD
  schedular: ReduceOnPlateau
  learning_rate_exp: 1
  num_workers: 0
  tolerance: 20
  epochs: 200


